# language: node_js
# node_js:
#   - "16"

# script:
# - 

language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - cd amazon-clone
  - npm install
  - npm test
  - npm run build